name: Release

on:
  push:
    tags:
    - '*'
env:
  GO_VERSION: "1.18"

jobs:
  build:
    name: Releasing trivy-plugin-webhook
    runs-on: ubuntu-20.04

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run Unit tests
      run: |
        make test

    - name: Build
      run: make build

    - name: Release
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}